<script type="text/javascript" src={{asset('adm/js/jquery-3.2.1.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/popper.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/bootstrap.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/jquery.dataTables.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/dataTables.bootstrap4.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/jquery.slimscroll.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/select2.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/moment.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/bootstrap-datetimepicker.min.js')}}></script>
<script type="text/javascript" src={{asset('adm/js/app.js')}}></script>
